// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyLocal(arg1) {
  return window['go']['main']['App']['CopyLocal'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectedPeers() {
  return window['go']['main']['App']['GetConnectedPeers']();
}

export function GetDiscovered() {
  return window['go']['main']['App']['GetDiscovered']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHistoryData(arg1) {
  return window['go']['main']['App']['GetHistoryData'](arg1);
}

export function GetPairRequests() {
  return window['go']['main']['App']['GetPairRequests']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function IsAddrOnline(arg1) {
  return window['go']['main']['App']['IsAddrOnline'](arg1);
}

export function IsPairedByName(arg1) {
  return window['go']['main']['App']['IsPairedByName'](arg1);
}

export function PairDiscovered(arg1) {
  return window['go']['main']['App']['PairDiscovered'](arg1);
}

export function PairWith(arg1) {
  return window['go']['main']['App']['PairWith'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemovePeer(arg1) {
  return window['go']['main']['App']['RemovePeer'](arg1);
}

export function RemovePeerByName(arg1) {
  return window['go']['main']['App']['RemovePeerByName'](arg1);
}

export function RespondPairRequest(arg1, arg2) {
  return window['go']['main']['App']['RespondPairRequest'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function ScanNow() {
  return window['go']['main']['App']['ScanNow']();
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}
