// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {engine} from '../models';

export function CopyLocal(arg1:string):Promise<string>;

export function GetAutostart():Promise<boolean>;

export function GetConfig():Promise<main.ConfigView|string>;

export function GetConnectedPeers():Promise<Array<string>>;

export function GetDiscovered():Promise<Array<engine.DiscoveredPeer>>;

export function GetHistory():Promise<Array<main.HistoryView>|string>;

export function GetHistoryData(arg1:string):Promise<string|string>;

export function GetPairRequests():Promise<Array<engine.PairRequest>>;

export function GetPeers():Promise<Array<main.PeerView>>;

export function IsAddrOnline(arg1:string):Promise<boolean>;

export function IsPairedByName(arg1:string):Promise<boolean>;

export function PairDiscovered(arg1:string):Promise<main.PeerView|string>;

export function PairWith(arg1:string):Promise<main.PeerView|string>;

export function Quit():Promise<void>;

export function RemovePeer(arg1:string):Promise<string>;

export function RemovePeerByName(arg1:string):Promise<string>;

export function RespondPairRequest(arg1:string,arg2:boolean):Promise<string>;

export function SaveConfig(arg1:string,arg2:number):Promise<string>;

export function ScanNow():Promise<void>;

export function SetAutostart(arg1:boolean):Promise<string>;

export function SetTheme(arg1:string):Promise<string>;

export function ShowMainWindow():Promise<void>;
